import React from "react";

export const Tehsilsbydistrict = {
    "Bagh": ["DhirKot", "Harighel", "Bagh"],
    "Bhimber": ["Barnala", "Bhimber", "Samahni"],
    "Jhelum Valley": ["Chikar", "Lattian", "Leepa"],
    "Haveli": ["Haveli", "Khurshidabad", "Mumtazabad"],
    "Kotli": ["Charhoi", "Dulliya Jattan", "Fatehpur Thakiala", "Khui Ratta", "Kotli", "Sehnsa"],
    "Mirpur": ["Dadyal", "Mirpur"],
    "Muzaffarabad": ["Naseerabad", "Muzaffarabad"],
    "Neelum": ["Athmuqam", "Sharda"],
    "Poonch": ["Abbaspur", "Hajira", "Rawalkot", "Thorar"],
    "Sudhnoti": ["Baluch", "Mong", "Pallandri", "Tarar Khal"],

    "Awaran": ["Awaran", "Jhal Jao", "Mashkai", "Gishekore"],
    "Barkhan": ["Barkhan", "Rakhni"],
    "Chagai": ["Dalbandin", "Nokkundi", "Taftan", "Chagai"],
    "Dera Bugti": ["Dera Bugti", "Phelawagh", "Sui"],
    "Gwadar": ["Gwadar", "Jiwani", "Ormara", "Pasni", "Sunster"],
    "Harnai": ["Harnai", "Shahrugh"],
    "Jaffarabad": ["Gandakha", "Jhat Pat", "Usta Mohammad"],
    "Jhal Magsi": ["Gandawa", "Jhal Magsi"],
    "Kachhi": ["Dhadar", "Mach", "Sanni", "Balanari", "Khattan"],
    "Kalat": ["Kalat", "Khaliqabad"],
    "Kech": ["Kech (Turbat)", "Buleda", "Desht", "Mand", "Tump"],
    "Kharan": ["Kharan", "Sarkharan", "Tomulk"],
    "Khuzdar": ["Khuzdar", "Mola", "Naal", "Wadh", "Zehri"],
    "Killa Abdullah": ["Killa Abdullah", "Dobandi", "Gulistan", "Killa Saifullah", "Muslim Bagh"],
    "Killa Saifullah": ["Killa Saifullah", "Muslim Bagh"],
    "Kahan": ["Kahan", "Kohlu", "Mawand"],
    "Lasbela": ["Bela",
        "Dureji",
        "Gaddani",
        "Hub",
        "Kanraj",
        "Sonmiani",
        "Uthal",
        "Lakhra",
        "Lairi",
    ],
    "Lehri": ["Bagh", "Lehri"],
    "Loralai": ["Loralai",
        "Mekhtar",
    ],
    "Mastung": ["Dasht Spenzend",
        "Kirdgap",
        "Mastung",
    ],
    "Musakhel": [
        "Drug",
        "Kingri",
        "Musakhel",

    ],
    "Nasirabad": ["Chattar",
        "Dera Murad Jamali",
        "Tamboo",
    ],
    "Nushki": ["Nushki"],
    "Panjgur": ["Gowargo",
        "Jaheen Parome",
        "Panjgur",
        "Gichk",
    ],
    "Pishin": ["Barshore",
        "Huramzai",
        "Karezat",
        "Pishin",
        "Saranan",
    ],
    "Quetta": ["Panjpai",
        "Quetta City",
        "Quetta Saddar",
    ],
    "Sherani": ["Sherani"],
    "Sibi": ["Sibi"],
    "Sohbatpur": ["Sohbatpur"],
    "Washuk": ["Mashkhel",
        "Basima",
        "Washuk",
        "Nag",
        "Shaogari",
    ],
    "Zhob": [
        "Kakar Khurasan",
        "Zhob",
    ],
    "Ziarat": ["Ziarat", "Sinjawi"],
    "Shaheed Sikandarabad": ["Surab", "Duki"],
    "Chaman": ["Chaman"],

    "Astore": ["Astore",
        "Shounter",
    ],
    "Diamir": ["Chilas"],
    "Ghanche": ["Daghnoi", "Khaplu", "Mashabbrum"],
    "Ghizer": ["Ishkoman",
        "Punial",
    ],
    "Gilgit": ["Gilgit"],
    "Hunza": ["Ali Abad",
        "Gojal",
    ],
    "Skardu": ["Gamba",
        "Skardu",
    ],
    "Nagar": ["Nagar", "Sikandarabad"],
    "Kharmang": ["Gultari",
        "Kharmang",
    ],
    "Shigar": ["Darel"],
    "Darel": ["Darel"],
    "Tangir": ["Tangir"],
    "Gupis-Yasin": ["Gupis",
        "Phandar",
        "Yasin",
    ],
    "Rondu": ["Rondu"],

    "Islamabad" : ["Islambad"],

    "Abbottabad": ["Abbottabad",
        "Havelian",
        "Lora",
        "Lower Tanawal",
    ],
    "Bajaur": ["Bar Chamarkand",
        "Barang",
        "Khar",
        "Mamund",
        "Nawagai",
        "Salarzai",
        "Utman Khel",
    ],
    "Bannu": ["Bannu",
        "Baka Khel",
        "Domel",
        "Kakki",
        "Miryan",
        "Wazir",
    ],
    "Batagram": ["Allai",
        "Batagram",
    ],
    "Buner": [
        "Daggar",
        "Gagra",
        "Khado Khel",
        "Mandanr",

    ],
    "Charsadda": [
        "Charsadda",
        "Shabqadar",
        "Tangi",
    ],
    "Chitral Lower": [
        "Chitral",
        "Drosh",
        "Lotkoh",

    ],
    "Chitral Upper": [
        "Mastuj",
        "Mulkhow",

    ],
    "D. I. Khan": ["D. I. Khan",
        "Daraban",
        "Kulachi",
        "Paharpur",
        "Paroa",
        "Darazinda",
    ],
    "Hangu": ["Hangu", "Tall"],
    "Haripur": ["Ghazi", "Haripur", "Khanpur"],
    "Karak": ["Banda Daud Shah", "Takht-E-Nasrati", "Karak"],
    "Khyber": ["Bara",
        "Jamrud",
        "Landi Kotal",
        "Mulagori",
    ],
    "Kohat": ["Kohat",
        "Lachi",
        "Gumbat",
        "Darra Adam Khel",
    ],
    "Kohistan Lower": ["Pattan",
        "Bankad",
    ],
    "Kohistan Upper": ["Dassu",
        "Kandia",
        "Harban Basha",
        "Seo",
    ],
    "Kolai Palas Kohistan": ["Palas",
        "Battera Kolai",
    ],
    "Kurram": ["Central Kurram",
        "Lower Kurram",
        "Upper Kurram",
    ],
    "Lakki Marwat": [
        "Lakki Marwat",
        "Sarai Naurang",
        "Bettani",

    ],
    "Lower Dir": [
        "Adenzai",
        "Balambat",
        "Lalqila",
        "Munda",
        "Samarbagh",
        "Timergara",

    ],
    "Malakand": [
        "Bat Khela",
        "Dargai",

    ],
    "Mansehra": [
        "Bala Kot",
        "Mansehra",
        "Oghi",
        "Baffa Pakhal",
        "Darband",

    ],
    "Mardan": [
        "Katlang",
        "Mardan",
        "Takht Bhai",
        "Rustam",
        "Garhi Kapura",

    ],
    "Mohmand": [
        "Ambar",
        "Baizai",
        "Halimzai",
        "Khwazai",
        "Pandiali",
        "Prang Ghar",
        "Safi",
        "Yaka Ghund",

    ],
    "North Waziristan": [
        "Data Khel",
        "Dossali",
        "Garyum",
        "Ghulam Khan",
        "Mir Ali",
        "Miran Shah",
        "Razmak",
        "Shewa",
        "Spinwam",
        "Shawal",

    ],
    "Nowshera": [
        "Nowshera",
        "Pabbi",
        "Jehangira",

    ],
    "Orakzai": [
        "Central Orakzai",
        "Ismailzai",
        "Lower Orakzai",
        "Upper Orakzai",
    ],
    "Peshawar": [
        "Town-I",
        "Town-Ii",
        "Town-Iii",
        "Town-Iv",
        "Hassan Khel",

    ],
    "Shangla": [
        "Alpuri",
        "Bisham",
        "Chakisar",
        "Makhuzai",
        "Martoong",
        "Puran",

    ],
    "South Waziristan": [
        "Birmal",
        "Ladha",
        "Makin",
        "Sararogha",
        "Serwakai",
        "Tiarza",
        "Toi Khulla",
        "Wana",
    ],
    "Swabi": [
        "Lahor",
        "Swabi",
        "Topi",
        "Razar",

    ],
    "Swat": [
        "Babuzai",
        "Bahrain",
        "Barikot",
        "Charbagh",
        "Kabal",
        "Kalam",
        "Khwaza Khela",
        "Matta Kharirai",
        "Matta Sebujni",

    ],
    "Tank": ["Tank", "Jandola"],
    "Tor Ghar": [
        "Judba",
        "Khander",

    ],
    "Upper Dir": [
        "Barawal",
        "Dir",
        "Kalkot",
        "Khall",
        "Shrengal",
        "Wari",
        "Larjam",

    ],

    "Attock": [
        "Attock",
        "Fateh Jang",
        "Hasan Abdal",
        "Hazro",
        "Jand",
        "Pindi Gheb",

    ],
    "BahawalNagar": [
        "Bahawalnagar",
        "Chishtian",
        "Fort Abbas",
        "Haroonabad",
        "Minchinabad",

    ],
    "Bahawalpur": [
        "Ahmadpur East",
        "Bahawalpur",
        "Hasilpur",
        "Khairpur Tamewali",
        "Yazman",

    ],
    "Bhakkar": [
        "Bhakkar",
        "Darya Khan",
        "Kalur Kot",
        "Mankera",
    ],
    "Chakwal": [
        "Chakwal",
        "Choa Saidan Shah",
        "Kallar Kahar",
        "Tala Gang",
    ],
    "Chiniot": [
        "Bhawana",
        "Chiniot",
        "Lalian",

    ],
    "Dera Ghazi Khan": [
        "D.G Khan (Tribal Area)",
        "Dera Ghazi Khan",
        "Kot Chatta",
        "Taunsa",
    ],
    "Faisalabad": [
        "Chak Jhumra",
        "Faisalabad City",
        "Faisalabad Sadar",
        "Jaranwala",
        "Summundri",
        "Tandlian Wala",

    ],
    "Gujranwala": [
        "Gujranwala",
        "Kamoke",
        "Nowshera Virkan",
        "Wazirabad",

    ],
    "Gujrat": [
        "Gujrat",
        "Kharian",
        "Sarai Alamgir",
    ],
    "Hafizabad": ["Hafizabad",
        "Pindi Bhattian",
    ],
    "Jhang": [
        "Ahmadpur Sial",
        "Jhang",
        "Shorkot",
        "Athara Hazari",

    ],
    "Jhelum": [
        "Dina",
        "Jhelum",
        "Pind Dadan Khan",
        "Sohawa",

    ],
    "Kasur": [
        "Chunian",
        "Kasur",
        "Kot Radha Kishen",
        "Pattoki",

    ],
    "Khanewal": [
        "Jahanian",
        "Kabirwala",
        "Khanewal",
        "Mian Channu",

    ],
    "Khushab": [
        "Khushab",
        "Naushera",
        "Noorpur",
        "Quaidabad",
    ],
    "Lahore": ["Lahore City", "Lahore Cantt"],
    "Leiah": ["Choubara",
        "Karor Lal Esan",
        "Leiah",
    ],
    "Lodhran": [
        "Dunyapur",
        "Kahror Pacca",
        "Lodhran",

    ],
    "Mandi Bahauddin": [
        "Malakwal",
        "Mandi Bahauddin",
        "Phalia",

    ],
    "Mianwali": [
        "Isakhel",
        "Mianwali",
        "Piplan",
    ],
    "Muzaffargarh": [
        "Alipur",
        "Jatoi",
        "Kot Addu",
        "Muzaffargarh",
    ],
    "Nankana Sahib": [
        "Nankana Sahib",
        "Sangla Hill",
        "Shah Kot",
    ],
    "Narowal": [
        "Narowal",
        "Shakargarh",
        "Zafarwal",

    ],
    "Okara": [
        "Narowal",
        "Shakargarh",
        "Zafarwal",

    ],
    "Pakpattan": [
        "Arif Wala",
        "Pakpattan",
    ],
    "Rahim Yar Khan": [
        "Khanpur",
        "Liaqatpur",
        "Rahim Yar Khan",
        "Sadiqabad",
    ],
    "Rajanpur": [
        "Jampur",
        "Rajanpur",
        "Rajanpur (Tribal Area)",
        "Rojhan",
    ],
    "Rawalpindi": [
        "Gujar Khan",
        "Kahuta",
        "Kallar Sayaddan",
        "Kotli Sattian",
        "Murree",
        "Rawalpindi",
        "Taxila",

    ],
    "Sahiwal": [
        "Chichawatni",
        "Sahiwal",

    ],
    "Sargodha": [
        "Bhalwal",
        "Kot Momin",
        "Sahiwal",
        "Sargodha",
        "Shahpur",
        "Sillanwali",
        "Bhera",

    ],
    "Sheikhupura": [
        "Ferozewala",
        "Muridke",
        "Safdarabad",
        "Sharak Pur",
        "Sheikhupura",

    ],
    "Sialkot": [
        "Daska",
        "Pasrur",
        "Sambrial",
        "Sialkot",

    ],
    "Toba Tek Singh": [
        "Gojra",
        "Kamalia",
        "Toba Tek Singh",
        "Pir Mahal",

    ],
    "Vehari": [
        "Burewala",
        "Mailsi",
        "Vehari",
    ],

    "Badin": [
        "Badin",
        "Matli",
        "Shaheed Fazil Rahu",
        "Talhar",
        "Tando Bago",

    ],
    "Central Karachi": [
        "Gulberg Town",
        "Liaqatabad Town",
        "New Karachi Town",
        "North Nazimabad Town",

    ],
    "Dadu": [
        "Dadu",
        "Johi",
        "Khairpur Nathan Shah",
        "Mehar",

    ],
    "East Karachi": [
        "Gulshan Iqbal Town",
        "Jamshaid Town",

    ],
    "Ghotki": [
        "Daharki",
        "Ghotki",
        "Khangarh",
        "Mirpur Mathelo",
        "Ubauro",

    ],
    "Hyderabad": [
        "Hyderabad",
        "Hyderabad City",
        "Latifabad",
        "Qasimabad",
    ],
    "Jacobabad": [
        "Garhi Khairo",
        "Jacobabad",
        "Thul",
    ],
    "Jamshoro": [
        "Kotri",
        "Manjhand",
        "Sehwan Sharif",
        "Thano Bula Khan",
    ],
    "Kambar Shahdad Kot": [
        "Meero Khan",
        "Nasir Abad",
        "Qambar Ali Khan",
        "Qubo Saeed Khan",
        "Shahdad Kot",
        "Sijawal Junejo",
        "Warah",
    ],
    "Kashmore": [
        "Kandh Kot",
        "Kashmore",
        "Tangwani",
    ],
    "Khairpur": [
        "Faiz Ganj",
        "Gambat",
        "Khairpur",
        "Kingri",
        "Kot Diji",
        "Nara",
        "Sobho Dero",
        "Thari Meer Wah",
    ],
    "Korangi Karachi": [
        "Korangi Town",
        "Landhi Town",
        "Shah Faisal Town",
    ],
    "Larkana": [
        "Baqrani",
        "Dokri",
        "Larkana",
        "Rato Dero",
    ],
    "Malir Karachi": [
        "Bin Qasim Town",
        "Gadap Town",
        "Malir Town",
    ],
    "Matiari": [
        "Hala",
        "Matiari",
        "Saeedabad",
    ],
    "Mirpur Khas": [
        "Digri",
        "Hussain Bux Muree",
        "Jhudo",
        "Kot Ghulam Muhammad",
        "Mirpur Khas",
        "Shuja Abad",
        "Sindhri",
    ],
    "Naushahro Feroze": [
        "Bhiria",
        "Kandiaro",
        "Mehrab Pur",
        "Moro",
        "Naushahro Feroze",
    ],
    "Sanghar": [
        "Jam Nawaz Ali",
        "Khipro",
        "Sanghar",
        "Shahdadpur",
        "Sinjhoro",
        "Tando Adam",
    ],
    "Shaheed Benazir Abad": [
        "Daulat Pur",
        "Daur",
        "Nawabshah",
        "Sakrand",
    ],
    "Shikarpur": [
        "Garhi Yasin",
        "Khanpur",
        "Lakhi",
        "Shikarpur",
    ],
    "South Karachi": [
        "Kemari Town",
        "Liyari Town",
        "Saddar Town",
    ],
    "Sujawal": [
        "Jati",
        "Kharo Chan",
        "Mirpur Bathoro",
        "Shah Bunder",
        "Sujawal",
    ],
    "Sukkur": [
        "New Sukkur",
        "Pano Aqil",
        "Rohri",
        "Salehpat",
        "Sukkur",
    ],
    "Tando Allahyar": [
        "Chamber",
        "Jhando Mari",
        "Tando Allahyar",
    ],
    "Tando Muhammad Khan": [
        "Bulri Shah Karim",
        "Tando Ghulam Hyder",
        "Tando Muhammad Khan",
    ],
    "Tharparkar": [
        "Chachro",
        "Dahli",
        "Diplo",
        "Islam Kot",
        "Mithi",
        "Nagar Parkar",
        "Kaloi",
    ],
    "Thatta": [
        "Ghorabari",
        "Keti Bunder",
        "Mirpur Sakro",
        "Thatta",
    ],
    "Umer Kot": [
        "Kunri",
        "Pithoro",
        "Samaro",
        "Umer Kot",
    ],
    "West Karachi": [
        "Baldia Town",
        "Orangi Town",
        "Site Town",
    ],
}