import React from "react";

export const districtsByProvince = {
    "Sindh": [
        'Badin',
        'Central Karachi',
        'Dadu',
        'East Karachi',
        'Ghotki',
        'Hyderabad',
        'Jacobabad',
        'Jamshoro',
        'Kambar Shahdad Kot',
        'Kashmor',
        'Khairpur',
        'Korangi Karachi',
        'Larkana',
        'Malir karachi',
        'Matiari',
        'Mirpur Khas',
        'Naushahro Feroze',
        'Sanghar',
        'Shaheed Benazir Abad',
        'Shikarpur',
        'South Karachi',
        'Sujawal',
        'Tando Allahyar',
        'Tando Muhammad Khan',
        'Tharparkar',
        'Thatta',
        'Umer Kot',
        'West Karachi',
    ],
    "Gilgit Baltistan": [
        'Astore',
        'Diamir',
        'Darel',
        'Gilgit',
        'Ghizer',
        'Ghanchi',
        'Gupis',
        'Hunza',
        'Kharmang',
        'Nagar',
        'Rondu',
        'Shigar',
        'Skardu',
        'Tangir',
        'Yasin',
    ],
    "Balochistan": [
        "Awaran",
        "Barkhan",
        "Chaman",
        "Chagai",
        "Duki",
        "Dera Bugti",
        "Gwadar",
        "Harnai",
        "Jaffarabad",
        "Jhal Magsi",
        "Khuzdar",
        "Kachhi",
        "Kalat",
        "Kech",
        "Kharan",
        "Khuzdar",
        "Killa Abdulla",
        "Killa Saifulla",
        "Kohlu",
        "Lasbela",
        "Lehri",
        "Lohralai",
        "Mastung",
        "Nushki",
        "Nasirabad",
        "Panjgur",
        "Pishin",
        "Panjgur",
        "Quetta",
        "Sibi",
        "Shaheed Sikandarabad",
        "Sohbatpur",
        "Sherani",
        "Washuk",
        "Zhob",
        "Ziarat",
        "Zhob",
    ],
    "Punjab":[
        "Attock",
        "BahawalNagar",
        "Bahawalpur",
        "Chakwal",
        "Chiniot",
        "Dera Ghazi Khan",
        "Faisalabad",
        "Gujranwal",
        "Gujrat",
        "Hafizabad",
        "Jhang",
        "Jhelum",
        "Kasur",
        "Khanewal",
        "Khushab",
        "Lahore",
        "Leiah",
        "Lodhran",
        "Mandi Bahauddin",
        "Mianwali",
        "Multan",
        "Muzaffargarh",
        "Narowal",
        "Okara",
        "Pakpattan",
        "Rahim Yar Khan",
        "Rajanpur",
        "Rawalpindi",
        "Sahiwal",
        "Sargodha",
        "Sheikhupura",
        "Sialkot",
        "Toba Tek Singh",
        "Vehari",
    ],
    "Khyber Pakhtunkhwa":[
        "Abbottabad",
        "Bajaur",
        "Batagram",
        "Charsadda",
        "Chitral Lower",
        "Chitral Upper",
        "D. I. Khan",
        "Hangu",
        "Haripur",
        "Karak",
        "Khyber",
        "Kohat",
        "Kohistan Lower",
        "Kohistan Upper",
        "Kolai Palas Kohistan",
        "Kurram",
        "Lakki Marwat",
        "Lower Dir",
        "Malakand",
        "Mansehra",
        "Mardan",
        "Mohmand",
        "North Waziristan",
        "Nowshera",
        "Orakzai",
        "Peshawar",
        "Shangla",
        "South Waziristan",
        "Swabi",
        "Swat",
        "Tank",
        "Tor Ghar",
        "Upper Dir",
    ],
    "Azad Kashmir":[
        "Bagh",
        "Bhimber",
        "Haveli",
        "Jhelum Valley",
        "Kotli",
        "Mirpur",
        "Muzaffarabad",
        "Neelum",
        "Poonch",
        "Sudhnoti",
    ],
    "Islamabad" : ["Islamabad"],
}